<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260210122000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create processing_job and idempotency_entry tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE processing_job (id VARCHAR(36) NOT NULL, asset_uuid VARCHAR(36) NOT NULL, job_type VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, claimed_by VARCHAR(32) DEFAULT NULL, lock_token VARCHAR(64) DEFAULT NULL, locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, result_payload JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_processing_job_status ON processing_job (status)');
        $this->addSql('CREATE INDEX idx_processing_job_locked_until ON processing_job (locked_until)');

        $this->addSql('CREATE TABLE idempotency_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_id VARCHAR(64) NOT NULL, method VARCHAR(8) NOT NULL, path VARCHAR(255) NOT NULL, idempotency_key VARCHAR(128) NOT NULL, request_hash VARCHAR(64) NOT NULL, response_status INT NOT NULL, response_body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_idempotency_key_scope ON idempotency_entry (actor_id, method, path, idempotency_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE idempotency_entry');
        $this->addSql('DROP TABLE processing_job');
    }
}
