<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260403170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the initial application schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE app_user (
    id VARCHAR(32) NOT NULL,
    email VARCHAR(180) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    roles JSON NOT NULL,
    email_verified BOOLEAN NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_app_user_email ON app_user (email)');
        $this->addSql("INSERT INTO app_user (id, email, password_hash, roles, email_verified, created_at, updated_at) VALUES ('bootstrapadmin0001', 'admin@retaia.local', '$2y$12$6AGCXyao1Z/Rc2ippIQ8xOhoWwyKr1TaReDVu/jayjEclIawUJjUm', '[\"ROLE_ADMIN\"]', TRUE, NOW(), NOW())");

        $this->addSql(<<<'SQL'
CREATE TABLE password_reset_token (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE INDEX idx_password_reset_token_user_id ON password_reset_token (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_password_reset_token_hash ON password_reset_token (token_hash)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE webauthn_device (
    id VARCHAR(36) NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    credential_id VARCHAR(191) NOT NULL,
    device_label VARCHAR(128) NOT NULL,
    webauthn_fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE INDEX idx_webauthn_device_user ON webauthn_device (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_webauthn_device_user_credential ON webauthn_device (user_id, credential_id)');
        $this->addSql('ALTER TABLE webauthn_device ADD CONSTRAINT fk_webauthn_device_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE asset (
    uuid VARCHAR(36) NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    state VARCHAR(32) NOT NULL,
    tags JSON NOT NULL,
    notes TEXT DEFAULT NULL,
    fields JSON NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(uuid)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_asset_uuid ON asset (uuid)');

        $this->addSql(<<<'SQL'
CREATE TABLE processing_job (
    id VARCHAR(36) NOT NULL,
    asset_uuid VARCHAR(36) NOT NULL,
    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    claimed_by VARCHAR(32) DEFAULT NULL,
    lock_token VARCHAR(64) DEFAULT NULL,
    locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    result_payload JSON DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    state_version VARCHAR(64) NOT NULL DEFAULT '1',
    correlation_id VARCHAR(64) DEFAULT NULL,
    fencing_token INT DEFAULT NULL,
    claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    completed_by VARCHAR(32) DEFAULT NULL,
    completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    failed_by VARCHAR(32) DEFAULT NULL,
    failed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY(id),
    CONSTRAINT chk_processing_job_status CHECK (status IN ('pending', 'claimed', 'completed', 'failed')),
    CONSTRAINT chk_processing_job_fencing_positive CHECK (fencing_token IS NULL OR fencing_token > 0),
    CONSTRAINT chk_processing_job_claimed_fields CHECK (
        status <> 'claimed'
        OR (
            claimed_by IS NOT NULL
            AND claimed_at IS NOT NULL
            AND lock_token IS NOT NULL
            AND fencing_token IS NOT NULL
            AND locked_until IS NOT NULL
            AND completed_by IS NULL
            AND completed_at IS NULL
            AND failed_by IS NULL
            AND failed_at IS NULL
        )
    ),
    CONSTRAINT chk_processing_job_non_claimed_lock_fields CHECK (
        status = 'claimed'
        OR (
            lock_token IS NULL
            AND fencing_token IS NULL
            AND locked_until IS NULL
        )
    ),
    CONSTRAINT chk_processing_job_claimed_by_coherence CHECK (
        (status IN ('claimed', 'failed') AND claimed_by IS NOT NULL)
        OR (status IN ('pending', 'completed') AND claimed_by IS NULL)
    ),
    CONSTRAINT chk_processing_job_completed_fields CHECK (
        (status = 'completed' AND completed_by IS NOT NULL AND completed_at IS NOT NULL AND failed_by IS NULL AND failed_at IS NULL)
        OR (status <> 'completed' AND completed_by IS NULL AND completed_at IS NULL)
    ),
    CONSTRAINT chk_processing_job_failed_fields CHECK (
        (status = 'failed' AND failed_by IS NOT NULL AND failed_at IS NOT NULL AND completed_by IS NULL AND completed_at IS NULL)
        OR (status <> 'failed' AND failed_by IS NULL AND failed_at IS NULL)
    )
)
SQL);
        $this->addSql('CREATE INDEX idx_processing_job_status ON processing_job (status)');
        $this->addSql('CREATE INDEX idx_processing_job_locked_until ON processing_job (locked_until)');
        $this->addSql('CREATE UNIQUE INDEX uniq_processing_job_asset_type_version ON processing_job (asset_uuid, job_type, state_version)');
        $this->addSql('CREATE INDEX idx_processing_job_correlation_id ON processing_job (correlation_id)');
        $this->addSql('CREATE INDEX idx_processing_job_claimed_by_status ON processing_job (claimed_by, status)');
        $this->addSql('CREATE INDEX idx_processing_job_completed_by_completed_at ON processing_job (completed_by, completed_at)');
        $this->addSql('CREATE INDEX idx_processing_job_failed_by_failed_at ON processing_job (failed_by, failed_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE idempotency_entry (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    method VARCHAR(8) NOT NULL,
    path VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    response_status INT NOT NULL,
    response_body TEXT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_idempotency_key_scope ON idempotency_entry (actor_id, method, path, idempotency_key)');

        $this->addSql(<<<'SQL'
CREATE TABLE derived_upload_session (
    upload_id VARCHAR(24) NOT NULL,
    asset_uuid VARCHAR(36) NOT NULL,
    kind VARCHAR(64) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size_bytes INT NOT NULL,
    sha256 VARCHAR(64) DEFAULT NULL,
    status VARCHAR(16) NOT NULL,
    parts_count INT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(upload_id),
    CONSTRAINT chk_derived_upload_session_status CHECK (status IN ('open', 'completed')),
    CONSTRAINT chk_derived_upload_session_size CHECK (size_bytes >= 0),
    CONSTRAINT chk_derived_upload_session_parts CHECK (parts_count >= 0),
    CONSTRAINT chk_derived_upload_session_timestamps CHECK (updated_at >= created_at)
)
SQL);
        $this->addSql('CREATE INDEX idx_derived_upload_asset ON derived_upload_session (asset_uuid)');

        $this->addSql(<<<'SQL'
CREATE TABLE asset_derived_file (
    id VARCHAR(16) NOT NULL,
    asset_uuid VARCHAR(36) NOT NULL,
    kind VARCHAR(64) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size_bytes INT NOT NULL,
    sha256 VARCHAR(64) DEFAULT NULL,
    storage_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT chk_asset_derived_file_storage_path CHECK (btrim(storage_path) <> ''),
    CONSTRAINT chk_asset_derived_file_size CHECK (size_bytes >= 0)
)
SQL);
        $this->addSql('CREATE INDEX idx_asset_derived_asset ON asset_derived_file (asset_uuid)');
        $this->addSql('CREATE INDEX idx_asset_derived_asset_kind ON asset_derived_file (asset_uuid, kind)');

        $this->addSql(<<<'SQL'
CREATE TABLE batch_move_report (
    batch_id VARCHAR(16) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(batch_id)
)
SQL);
        $this->addSql('CREATE INDEX idx_batch_move_report_created_at ON batch_move_report (created_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE ingest_scan_file (
    path VARCHAR(1024) NOT NULL,
    size_bytes BIGINT NOT NULL,
    mtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    stable_count INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    storage_id VARCHAR(64) NOT NULL,
    PRIMARY KEY(storage_id, path)
)
SQL);
        $this->addSql('CREATE INDEX idx_ingest_scan_file_status ON ingest_scan_file (status)');
        $this->addSql('CREATE INDEX idx_ingest_scan_file_last_seen ON ingest_scan_file (last_seen_at)');
        $this->addSql('CREATE INDEX idx_ingest_scan_file_storage_status ON ingest_scan_file (storage_id, status)');

        $this->addSql(<<<'SQL'
CREATE TABLE ingest_path_audit (
    id VARCHAR(32) NOT NULL,
    asset_uuid VARCHAR(36) NOT NULL,
    from_path VARCHAR(1024) NOT NULL,
    to_path VARCHAR(1024) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE INDEX idx_ingest_path_audit_asset ON ingest_path_audit (asset_uuid)');
        $this->addSql('CREATE INDEX idx_ingest_path_audit_created_at ON ingest_path_audit (created_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE asset_operation_lock (
    id VARCHAR(32) NOT NULL,
    asset_uuid VARCHAR(36) NOT NULL,
    lock_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    released_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE INDEX idx_asset_operation_lock_asset ON asset_operation_lock (asset_uuid)');
        $this->addSql('CREATE INDEX idx_asset_operation_lock_active ON asset_operation_lock (released_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_asset_operation_lock_active_type ON asset_operation_lock (asset_uuid, lock_type) WHERE released_at IS NULL');

        $this->addSql(<<<'SQL'
CREATE TABLE ops_metric_event (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    metric_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE INDEX idx_ops_metric_event_key ON ops_metric_event (metric_key)');
        $this->addSql('CREATE INDEX idx_ops_metric_event_created_at ON ops_metric_event (created_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE ingest_unmatched_sidecar (
    path VARCHAR(1024) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    detected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(path)
)
SQL);
        $this->addSql('CREATE INDEX idx_ingest_unmatched_detected_at ON ingest_unmatched_sidecar (detected_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE agent_runtime (
    agent_id VARCHAR(36) NOT NULL,
    client_id VARCHAR(64) NOT NULL,
    agent_name VARCHAR(255) NOT NULL,
    agent_version VARCHAR(64) NOT NULL,
    os_name VARCHAR(32) DEFAULT NULL,
    os_version VARCHAR(64) DEFAULT NULL,
    arch VARCHAR(32) DEFAULT NULL,
    effective_capabilities TEXT NOT NULL,
    capability_warnings TEXT NOT NULL,
    last_register_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    last_heartbeat_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    max_parallel_jobs INT NOT NULL,
    feature_flags_contract_version VARCHAR(32) DEFAULT NULL,
    effective_feature_flags_contract_version VARCHAR(32) DEFAULT NULL,
    server_time_skew_seconds INT DEFAULT NULL,
    PRIMARY KEY(agent_id)
)
SQL);
        $this->addSql('CREATE INDEX idx_agent_runtime_last_seen_at ON agent_runtime (last_seen_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE user_auth_session (
    session_id VARCHAR(32) NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token VARCHAR(255) NOT NULL,
    access_expires_at BIGINT NOT NULL,
    refresh_expires_at BIGINT NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    email VARCHAR(180) NOT NULL,
    client_id VARCHAR(64) NOT NULL,
    client_kind VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    last_used_at BIGINT NOT NULL,
    PRIMARY KEY(session_id),
    CONSTRAINT chk_user_auth_session_not_blank CHECK (
        btrim(session_id) <> ''
        AND strpos(session_id, '|') = 0
        AND btrim(access_token) <> ''
        AND btrim(refresh_token) <> ''
        AND btrim(user_id) <> ''
        AND btrim(email) <> ''
        AND btrim(client_id) <> ''
        AND btrim(client_kind) <> ''
    ),
    CONSTRAINT chk_user_auth_session_access_expiry CHECK (access_expires_at > 0),
    CONSTRAINT chk_user_auth_session_refresh_window CHECK (refresh_expires_at >= access_expires_at),
    CONSTRAINT chk_user_auth_session_last_used CHECK (last_used_at >= created_at)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_auth_session_refresh_token ON user_auth_session (refresh_token)');
        $this->addSql('CREATE INDEX idx_user_auth_session_user_id ON user_auth_session (user_id)');
        $this->addSql('CREATE INDEX idx_user_auth_session_refresh_expires_at ON user_auth_session (refresh_expires_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE user_two_factor_state (
    user_id VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL,
    pending_secret_encrypted TEXT DEFAULT NULL,
    secret_encrypted TEXT DEFAULT NULL,
    recovery_code_hashes TEXT NOT NULL,
    legacy_recovery_code_sha256 TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY(user_id),
    CONSTRAINT chk_user_two_factor_state_user_id CHECK (btrim(user_id) <> ''),
    CONSTRAINT chk_user_two_factor_state_timestamps CHECK (created_at >= 0 AND updated_at >= created_at),
    CONSTRAINT chk_user_two_factor_state_enabled_secret CHECK (
        NOT enabled
        OR (secret_encrypted IS NOT NULL AND btrim(secret_encrypted) <> '')
    )
)
SQL);

        $this->addSql(<<<'SQL'
CREATE TABLE auth_client_registry (
    client_id VARCHAR(64) NOT NULL,
    client_kind VARCHAR(32) NOT NULL,
    secret_key VARCHAR(128) DEFAULT NULL,
    client_label VARCHAR(255) DEFAULT NULL,
    openpgp_public_key TEXT DEFAULT NULL,
    openpgp_fingerprint VARCHAR(40) DEFAULT NULL,
    registered_at VARCHAR(32) DEFAULT NULL,
    rotated_at VARCHAR(32) DEFAULT NULL,
    PRIMARY KEY(client_id)
)
SQL);
        $this->addSql("INSERT INTO auth_client_registry (client_id, client_kind, secret_key, client_label, openpgp_public_key, openpgp_fingerprint, registered_at, rotated_at) VALUES ('agent-default', 'AGENT', 'agent-secret', NULL, NULL, NULL, NULL, NULL)");
        $this->addSql("INSERT INTO auth_client_registry (client_id, client_kind, secret_key, client_label, openpgp_public_key, openpgp_fingerprint, registered_at, rotated_at) VALUES ('mcp-default', 'MCP', 'mcp-secret', NULL, NULL, NULL, NULL, NULL)");

        $this->addSql(<<<'SQL'
CREATE TABLE auth_client_access_token (
    client_id VARCHAR(64) NOT NULL,
    access_token TEXT NOT NULL,
    client_kind VARCHAR(32) NOT NULL,
    issued_at BIGINT NOT NULL,
    PRIMARY KEY(client_id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_client_access_token_token ON auth_client_access_token (access_token)');

        $this->addSql(<<<'SQL'
CREATE TABLE auth_device_flow (
    device_code VARCHAR(32) NOT NULL,
    user_code VARCHAR(16) NOT NULL,
    client_kind VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    interval_seconds INT NOT NULL,
    last_polled_at BIGINT NOT NULL,
    approved_client_id VARCHAR(64) DEFAULT NULL,
    approved_secret_key VARCHAR(128) DEFAULT NULL,
    PRIMARY KEY(device_code),
    CONSTRAINT chk_auth_device_flow_not_blank CHECK (
        btrim(device_code) <> ''
        AND btrim(user_code) <> ''
        AND btrim(client_kind) <> ''
    ),
    CONSTRAINT chk_auth_device_flow_status CHECK (status IN ('PENDING', 'APPROVED', 'DENIED', 'EXPIRED')),
    CONSTRAINT chk_auth_device_flow_expiry CHECK (expires_at >= created_at),
    CONSTRAINT chk_auth_device_flow_interval CHECK (interval_seconds > 0 AND last_polled_at >= 0),
    CONSTRAINT chk_auth_device_flow_approved_pair CHECK (
        (approved_client_id IS NULL AND approved_secret_key IS NULL)
        OR (approved_client_id IS NOT NULL AND approved_secret_key IS NOT NULL)
    ),
    CONSTRAINT chk_auth_device_flow_approved_status CHECK (
        status <> 'APPROVED'
        OR (approved_client_id IS NOT NULL AND approved_secret_key IS NOT NULL)
    )
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_device_flow_user_code ON auth_device_flow (user_code)');
        $this->addSql('CREATE INDEX idx_auth_device_flow_expires_at ON auth_device_flow (expires_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE auth_mcp_challenge (
    challenge_id VARCHAR(32) NOT NULL,
    client_id VARCHAR(64) NOT NULL,
    openpgp_fingerprint VARCHAR(40) NOT NULL,
    challenge VARCHAR(128) NOT NULL,
    expires_at BIGINT NOT NULL,
    used BOOLEAN NOT NULL,
    used_at BIGINT DEFAULT NULL,
    PRIMARY KEY(challenge_id),
    CONSTRAINT chk_auth_mcp_challenge_not_blank CHECK (
        btrim(challenge_id) <> ''
        AND btrim(client_id) <> ''
        AND btrim(openpgp_fingerprint) <> ''
        AND btrim(challenge) <> ''
    ),
    CONSTRAINT chk_auth_mcp_challenge_expires CHECK (expires_at > 0),
    CONSTRAINT chk_auth_mcp_challenge_used_at CHECK ((used = FALSE AND used_at IS NULL) OR (used = TRUE AND used_at IS NOT NULL))
)
SQL);
        $this->addSql('CREATE INDEX idx_auth_mcp_challenge_expires_at ON auth_mcp_challenge (expires_at)');

        $this->addSql(<<<'SQL'
CREATE TABLE agent_public_key (
    agent_id VARCHAR(36) NOT NULL,
    openpgp_fingerprint VARCHAR(40) NOT NULL,
    openpgp_public_key TEXT NOT NULL,
    updated_at INT NOT NULL,
    PRIMARY KEY(agent_id)
)
SQL);

        $this->addSql(<<<'SQL'
CREATE TABLE agent_signature_nonce (
    nonce_key VARCHAR(64) NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    expires_at INT NOT NULL,
    consumed_at INT NOT NULL,
    PRIMARY KEY(nonce_key)
)
SQL);
        $this->addSql('CREATE INDEX idx_agent_signature_nonce_expires_at ON agent_signature_nonce (expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE agent_signature_nonce');
        $this->addSql('DROP TABLE agent_public_key');
        $this->addSql('DROP TABLE auth_mcp_challenge');
        $this->addSql('DROP TABLE auth_device_flow');
        $this->addSql('DROP TABLE auth_client_access_token');
        $this->addSql('DROP TABLE auth_client_registry');
        $this->addSql('DROP TABLE user_two_factor_state');
        $this->addSql('DROP TABLE user_auth_session');
        $this->addSql('DROP TABLE agent_runtime');
        $this->addSql('DROP TABLE ingest_unmatched_sidecar');
        $this->addSql('DROP TABLE ops_metric_event');
        $this->addSql('DROP TABLE asset_operation_lock');
        $this->addSql('DROP TABLE ingest_path_audit');
        $this->addSql('DROP TABLE ingest_scan_file');
        $this->addSql('DROP TABLE batch_move_report');
        $this->addSql('DROP TABLE asset_derived_file');
        $this->addSql('DROP TABLE derived_upload_session');
        $this->addSql('DROP TABLE idempotency_entry');
        $this->addSql('DROP TABLE processing_job');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE webauthn_device');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('DROP TABLE app_user');
    }
}
