<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260210183000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ops_metric_event table for lightweight metrics and alerts';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ops_metric_event (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, metric_key VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ops_metric_event_key ON ops_metric_event (metric_key)');
        $this->addSql('CREATE INDEX idx_ops_metric_event_created_at ON ops_metric_event (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ops_metric_event');
    }
}

