<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXImpN8I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXImpN8I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXImpN8I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXImpN8I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXImpN8I\App_KernelDevDebugContainer([
    'container.build_hash' => 'XImpN8I',
    'container.build_id' => 'ecc09020',
    'container.build_time' => 1770551769,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXImpN8I');
